# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7f20a21f961b6c0712d8075b695d041c76b8ce83d9c5c5a8b4393fb81823a500c468e1fb8a51a0152db942423631b806a444ef8ce2aa78ec50701efa4d98fd26

test:
  secret_key_base: 6d4223fbb3534dd30db40d3bff243bcbd3072669de61d4551fbe1f2566374bdc9902cfbb71877a9ea6ddd1afda0c42e822bb10265832e0aabf77063a4371b59d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
